# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/scratch/signer/master/fips-ipc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/scratch/signer/master/fips-ipc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/scratch/signer/master/fips-ipc/CMakeFiles /mnt/scratch/signer/master/fips-ipc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/scratch/signer/master/fips-ipc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named udp_server

# Build rule for target.
udp_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 udp_server
.PHONY : udp_server

# fast build rule for target.
udp_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udp_server.dir/build.make CMakeFiles/udp_server.dir/build
.PHONY : udp_server/fast

#=============================================================================
# Target rules for targets named simplelogstash

# Build rule for target.
simplelogstash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simplelogstash
.PHONY : simplelogstash

# fast build rule for target.
simplelogstash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simplelogstash.dir/build.make CMakeFiles/simplelogstash.dir/build
.PHONY : simplelogstash/fast

#=============================================================================
# Target rules for targets named nsyslog

# Build rule for target.
nsyslog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nsyslog
.PHONY : nsyslog

# fast build rule for target.
nsyslog/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsyslog.dir/build.make CMakeFiles/nsyslog.dir/build
.PHONY : nsyslog/fast

#=============================================================================
# Target rules for targets named ebpf_utils

# Build rule for target.
ebpf_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ebpf_utils
.PHONY : ebpf_utils

# fast build rule for target.
ebpf_utils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebpf_utils.dir/build.make CMakeFiles/ebpf_utils.dir/build
.PHONY : ebpf_utils/fast

#=============================================================================
# Target rules for targets named simplefail2ban

# Build rule for target.
simplefail2ban: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simplefail2ban
.PHONY : simplefail2ban

# fast build rule for target.
simplefail2ban/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simplefail2ban.dir/build.make CMakeFiles/simplefail2ban.dir/build
.PHONY : simplefail2ban/fast

#=============================================================================
# Target rules for targets named poll_rbuf

# Build rule for target.
poll_rbuf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poll_rbuf
.PHONY : poll_rbuf

# fast build rule for target.
poll_rbuf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poll_rbuf.dir/build.make CMakeFiles/poll_rbuf.dir/build
.PHONY : poll_rbuf/fast

#=============================================================================
# Target rules for targets named ip_string_benchmark

# Build rule for target.
ip_string_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ip_string_benchmark
.PHONY : ip_string_benchmark

# fast build rule for target.
ip_string_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ip_string_benchmark.dir/build.make CMakeFiles/ip_string_benchmark.dir/build
.PHONY : ip_string_benchmark/fast

#=============================================================================
# Target rules for targets named hashfunc_benchmark

# Build rule for target.
hashfunc_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hashfunc_benchmark
.PHONY : hashfunc_benchmark

# fast build rule for target.
hashfunc_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashfunc_benchmark.dir/build.make CMakeFiles/hashfunc_benchmark.dir/build
.PHONY : hashfunc_benchmark/fast

#=============================================================================
# Target rules for targets named libbpf

# Build rule for target.
libbpf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libbpf
.PHONY : libbpf

# fast build rule for target.
libbpf/fast:
	$(MAKE) $(MAKESILENT) -f external/CMakeFiles/libbpf.dir/build.make external/CMakeFiles/libbpf.dir/build
.PHONY : libbpf/fast

#=============================================================================
# Target rules for targets named libbpf-build

# Build rule for target.
libbpf-build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libbpf-build
.PHONY : libbpf-build

# fast build rule for target.
libbpf-build/fast:
	$(MAKE) $(MAKESILENT) -f external/CMakeFiles/libbpf-build.dir/build.make external/CMakeFiles/libbpf-build.dir/build
.PHONY : libbpf-build/fast

#=============================================================================
# Target rules for targets named bpftool

# Build rule for target.
bpftool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bpftool
.PHONY : bpftool

# fast build rule for target.
bpftool/fast:
	$(MAKE) $(MAKESILENT) -f external/CMakeFiles/bpftool.dir/build.make external/CMakeFiles/bpftool.dir/build
.PHONY : bpftool/fast

#=============================================================================
# Target rules for targets named bpftool-build

# Build rule for target.
bpftool-build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bpftool-build
.PHONY : bpftool-build

# fast build rule for target.
bpftool-build/fast:
	$(MAKE) $(MAKESILENT) -f external/CMakeFiles/bpftool-build.dir/build.make external/CMakeFiles/bpftool-build.dir/build
.PHONY : bpftool-build/fast

#=============================================================================
# Target rules for targets named ip_hashtable

# Build rule for target.
ip_hashtable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ip_hashtable
.PHONY : ip_hashtable

# fast build rule for target.
ip_hashtable/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/CMakeFiles/ip_hashtable.dir/build.make src/lib/CMakeFiles/ip_hashtable.dir/build
.PHONY : ip_hashtable/fast

#=============================================================================
# Target rules for targets named ip_to_str

# Build rule for target.
ip_to_str: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ip_to_str
.PHONY : ip_to_str

# fast build rule for target.
ip_to_str/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/CMakeFiles/ip_to_str.dir/build.make src/lib/CMakeFiles/ip_to_str.dir/build
.PHONY : ip_to_str/fast

#=============================================================================
# Target rules for targets named ip_llist

# Build rule for target.
ip_llist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ip_llist
.PHONY : ip_llist

# fast build rule for target.
ip_llist/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/CMakeFiles/ip_llist.dir/build.make src/lib/CMakeFiles/ip_llist.dir/build
.PHONY : ip_llist/fast

#=============================================================================
# Target rules for targets named shm_ringbuf

# Build rule for target.
shm_ringbuf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shm_ringbuf
.PHONY : shm_ringbuf

# fast build rule for target.
shm_ringbuf/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/CMakeFiles/shm_ringbuf.dir/build.make src/lib/CMakeFiles/shm_ringbuf.dir/build
.PHONY : shm_ringbuf/fast

#=============================================================================
# Target rules for targets named uring_getline

# Build rule for target.
uring_getline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uring_getline
.PHONY : uring_getline

# fast build rule for target.
uring_getline/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/CMakeFiles/uring_getline.dir/build.make src/lib/CMakeFiles/uring_getline.dir/build
.PHONY : uring_getline/fast

#=============================================================================
# Target rules for targets named spookyc

# Build rule for target.
spookyc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spookyc
.PHONY : spookyc

# fast build rule for target.
spookyc/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/CMakeFiles/spookyc.dir/build.make src/lib/CMakeFiles/spookyc.dir/build
.PHONY : spookyc/fast

src/lib/ebpf_utils.o: src/lib/ebpf_utils.c.o
.PHONY : src/lib/ebpf_utils.o

# target to build an object file
src/lib/ebpf_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebpf_utils.dir/build.make CMakeFiles/ebpf_utils.dir/src/lib/ebpf_utils.c.o
.PHONY : src/lib/ebpf_utils.c.o

src/lib/ebpf_utils.i: src/lib/ebpf_utils.c.i
.PHONY : src/lib/ebpf_utils.i

# target to preprocess a source file
src/lib/ebpf_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebpf_utils.dir/build.make CMakeFiles/ebpf_utils.dir/src/lib/ebpf_utils.c.i
.PHONY : src/lib/ebpf_utils.c.i

src/lib/ebpf_utils.s: src/lib/ebpf_utils.c.s
.PHONY : src/lib/ebpf_utils.s

# target to generate assembly for a file
src/lib/ebpf_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebpf_utils.dir/build.make CMakeFiles/ebpf_utils.dir/src/lib/ebpf_utils.c.s
.PHONY : src/lib/ebpf_utils.c.s

src/programs/nsyslog.o: src/programs/nsyslog.c.o
.PHONY : src/programs/nsyslog.o

# target to build an object file
src/programs/nsyslog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsyslog.dir/build.make CMakeFiles/nsyslog.dir/src/programs/nsyslog.c.o
.PHONY : src/programs/nsyslog.c.o

src/programs/nsyslog.i: src/programs/nsyslog.c.i
.PHONY : src/programs/nsyslog.i

# target to preprocess a source file
src/programs/nsyslog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsyslog.dir/build.make CMakeFiles/nsyslog.dir/src/programs/nsyslog.c.i
.PHONY : src/programs/nsyslog.c.i

src/programs/nsyslog.s: src/programs/nsyslog.c.s
.PHONY : src/programs/nsyslog.s

# target to generate assembly for a file
src/programs/nsyslog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsyslog.dir/build.make CMakeFiles/nsyslog.dir/src/programs/nsyslog.c.s
.PHONY : src/programs/nsyslog.c.s

src/programs/simplefail2ban.o: src/programs/simplefail2ban.c.o
.PHONY : src/programs/simplefail2ban.o

# target to build an object file
src/programs/simplefail2ban.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simplefail2ban.dir/build.make CMakeFiles/simplefail2ban.dir/src/programs/simplefail2ban.c.o
.PHONY : src/programs/simplefail2ban.c.o

src/programs/simplefail2ban.i: src/programs/simplefail2ban.c.i
.PHONY : src/programs/simplefail2ban.i

# target to preprocess a source file
src/programs/simplefail2ban.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simplefail2ban.dir/build.make CMakeFiles/simplefail2ban.dir/src/programs/simplefail2ban.c.i
.PHONY : src/programs/simplefail2ban.c.i

src/programs/simplefail2ban.s: src/programs/simplefail2ban.c.s
.PHONY : src/programs/simplefail2ban.s

# target to generate assembly for a file
src/programs/simplefail2ban.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simplefail2ban.dir/build.make CMakeFiles/simplefail2ban.dir/src/programs/simplefail2ban.c.s
.PHONY : src/programs/simplefail2ban.c.s

src/programs/simplelogstash.o: src/programs/simplelogstash.c.o
.PHONY : src/programs/simplelogstash.o

# target to build an object file
src/programs/simplelogstash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simplelogstash.dir/build.make CMakeFiles/simplelogstash.dir/src/programs/simplelogstash.c.o
.PHONY : src/programs/simplelogstash.c.o

src/programs/simplelogstash.i: src/programs/simplelogstash.c.i
.PHONY : src/programs/simplelogstash.i

# target to preprocess a source file
src/programs/simplelogstash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simplelogstash.dir/build.make CMakeFiles/simplelogstash.dir/src/programs/simplelogstash.c.i
.PHONY : src/programs/simplelogstash.c.i

src/programs/simplelogstash.s: src/programs/simplelogstash.c.s
.PHONY : src/programs/simplelogstash.s

# target to generate assembly for a file
src/programs/simplelogstash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simplelogstash.dir/build.make CMakeFiles/simplelogstash.dir/src/programs/simplelogstash.c.s
.PHONY : src/programs/simplelogstash.c.s

src/programs/udp_server.o: src/programs/udp_server.c.o
.PHONY : src/programs/udp_server.o

# target to build an object file
src/programs/udp_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udp_server.dir/build.make CMakeFiles/udp_server.dir/src/programs/udp_server.c.o
.PHONY : src/programs/udp_server.c.o

src/programs/udp_server.i: src/programs/udp_server.c.i
.PHONY : src/programs/udp_server.i

# target to preprocess a source file
src/programs/udp_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udp_server.dir/build.make CMakeFiles/udp_server.dir/src/programs/udp_server.c.i
.PHONY : src/programs/udp_server.c.i

src/programs/udp_server.s: src/programs/udp_server.c.s
.PHONY : src/programs/udp_server.s

# target to generate assembly for a file
src/programs/udp_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udp_server.dir/build.make CMakeFiles/udp_server.dir/src/programs/udp_server.c.s
.PHONY : src/programs/udp_server.c.s

src/utilities/hashfunc_benchmark.o: src/utilities/hashfunc_benchmark.c.o
.PHONY : src/utilities/hashfunc_benchmark.o

# target to build an object file
src/utilities/hashfunc_benchmark.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashfunc_benchmark.dir/build.make CMakeFiles/hashfunc_benchmark.dir/src/utilities/hashfunc_benchmark.c.o
.PHONY : src/utilities/hashfunc_benchmark.c.o

src/utilities/hashfunc_benchmark.i: src/utilities/hashfunc_benchmark.c.i
.PHONY : src/utilities/hashfunc_benchmark.i

# target to preprocess a source file
src/utilities/hashfunc_benchmark.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashfunc_benchmark.dir/build.make CMakeFiles/hashfunc_benchmark.dir/src/utilities/hashfunc_benchmark.c.i
.PHONY : src/utilities/hashfunc_benchmark.c.i

src/utilities/hashfunc_benchmark.s: src/utilities/hashfunc_benchmark.c.s
.PHONY : src/utilities/hashfunc_benchmark.s

# target to generate assembly for a file
src/utilities/hashfunc_benchmark.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashfunc_benchmark.dir/build.make CMakeFiles/hashfunc_benchmark.dir/src/utilities/hashfunc_benchmark.c.s
.PHONY : src/utilities/hashfunc_benchmark.c.s

src/utilities/ip_string_benchmark.o: src/utilities/ip_string_benchmark.c.o
.PHONY : src/utilities/ip_string_benchmark.o

# target to build an object file
src/utilities/ip_string_benchmark.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ip_string_benchmark.dir/build.make CMakeFiles/ip_string_benchmark.dir/src/utilities/ip_string_benchmark.c.o
.PHONY : src/utilities/ip_string_benchmark.c.o

src/utilities/ip_string_benchmark.i: src/utilities/ip_string_benchmark.c.i
.PHONY : src/utilities/ip_string_benchmark.i

# target to preprocess a source file
src/utilities/ip_string_benchmark.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ip_string_benchmark.dir/build.make CMakeFiles/ip_string_benchmark.dir/src/utilities/ip_string_benchmark.c.i
.PHONY : src/utilities/ip_string_benchmark.c.i

src/utilities/ip_string_benchmark.s: src/utilities/ip_string_benchmark.c.s
.PHONY : src/utilities/ip_string_benchmark.s

# target to generate assembly for a file
src/utilities/ip_string_benchmark.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ip_string_benchmark.dir/build.make CMakeFiles/ip_string_benchmark.dir/src/utilities/ip_string_benchmark.c.s
.PHONY : src/utilities/ip_string_benchmark.c.s

src/utilities/poll_rbuf.o: src/utilities/poll_rbuf.c.o
.PHONY : src/utilities/poll_rbuf.o

# target to build an object file
src/utilities/poll_rbuf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poll_rbuf.dir/build.make CMakeFiles/poll_rbuf.dir/src/utilities/poll_rbuf.c.o
.PHONY : src/utilities/poll_rbuf.c.o

src/utilities/poll_rbuf.i: src/utilities/poll_rbuf.c.i
.PHONY : src/utilities/poll_rbuf.i

# target to preprocess a source file
src/utilities/poll_rbuf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poll_rbuf.dir/build.make CMakeFiles/poll_rbuf.dir/src/utilities/poll_rbuf.c.i
.PHONY : src/utilities/poll_rbuf.c.i

src/utilities/poll_rbuf.s: src/utilities/poll_rbuf.c.s
.PHONY : src/utilities/poll_rbuf.s

# target to generate assembly for a file
src/utilities/poll_rbuf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poll_rbuf.dir/build.make CMakeFiles/poll_rbuf.dir/src/utilities/poll_rbuf.c.s
.PHONY : src/utilities/poll_rbuf.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bpftool"
	@echo "... bpftool-build"
	@echo "... libbpf"
	@echo "... libbpf-build"
	@echo "... ebpf_utils"
	@echo "... hashfunc_benchmark"
	@echo "... ip_hashtable"
	@echo "... ip_llist"
	@echo "... ip_string_benchmark"
	@echo "... ip_to_str"
	@echo "... nsyslog"
	@echo "... poll_rbuf"
	@echo "... shm_ringbuf"
	@echo "... simplefail2ban"
	@echo "... simplelogstash"
	@echo "... spookyc"
	@echo "... udp_server"
	@echo "... uring_getline"
	@echo "... src/lib/ebpf_utils.o"
	@echo "... src/lib/ebpf_utils.i"
	@echo "... src/lib/ebpf_utils.s"
	@echo "... src/programs/nsyslog.o"
	@echo "... src/programs/nsyslog.i"
	@echo "... src/programs/nsyslog.s"
	@echo "... src/programs/simplefail2ban.o"
	@echo "... src/programs/simplefail2ban.i"
	@echo "... src/programs/simplefail2ban.s"
	@echo "... src/programs/simplelogstash.o"
	@echo "... src/programs/simplelogstash.i"
	@echo "... src/programs/simplelogstash.s"
	@echo "... src/programs/udp_server.o"
	@echo "... src/programs/udp_server.i"
	@echo "... src/programs/udp_server.s"
	@echo "... src/utilities/hashfunc_benchmark.o"
	@echo "... src/utilities/hashfunc_benchmark.i"
	@echo "... src/utilities/hashfunc_benchmark.s"
	@echo "... src/utilities/ip_string_benchmark.o"
	@echo "... src/utilities/ip_string_benchmark.i"
	@echo "... src/utilities/ip_string_benchmark.s"
	@echo "... src/utilities/poll_rbuf.o"
	@echo "... src/utilities/poll_rbuf.i"
	@echo "... src/utilities/poll_rbuf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

